name: Reciping-FE Release (Main)

on:
  push:
    tags:
      - 'v*.*.*' # v1.0.0, v1.2.3 같은 버전 태그가 푸시될 때 실행

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: reciping-fe-service

jobs:
  build-and-push-release:
    name: Build and Push Release Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.ref_name }} # Git 태그 이름 (e.g., v1.0.1)을 이미지 태그로 사용
        run: | 
          # Pass the version as a build argument to Docker
          docker build --build-arg VITE_APP_VERSION=$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG